// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyONPTRGmqwgLWPWGz5HOf0-QKmV9RU74',
    appId: '1:372891657980:web:75205991ccdf67e0a6d979',
    messagingSenderId: '372891657980',
    projectId: 'sprintindex',
    authDomain: 'sprintindex.firebaseapp.com',
    storageBucket: 'sprintindex.firebasestorage.app',
    measurementId: 'G-QWF226H76S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD379cWQvzhvxY2b-LZASQrFJTpv8Dmcvo',
    appId: '1:372891657980:android:b64c5302a1fcdc19a6d979',
    messagingSenderId: '372891657980',
    projectId: 'sprintindex',
    storageBucket: 'sprintindex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Tsg4WDC0Nmpr88ce1iXg5wwfnxEAlnk',
    appId: '1:372891657980:ios:f41c5b6d44a6000ea6d979',
    messagingSenderId: '372891657980',
    projectId: 'sprintindex',
    iosBundleId: 'com.sprintindex.app',
    storageBucket: 'sprintindex.firebasestorage.app',
  );
}
